# Generated by Django 3.2.7 on 2021-09-04 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('text', models.TextField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='content2',
            name='author',
        ),
        migrations.RemoveField(
            model_name='content3',
            name='author',
        ),
        migrations.RemoveField(
            model_name='section1',
            name='author',
        ),
        migrations.RemoveField(
            model_name='section2',
            name='author',
        ),
        migrations.RemoveField(
            model_name='section3',
            name='author',
        ),
        migrations.DeleteModel(
            name='Content1',
        ),
        migrations.DeleteModel(
            name='Content2',
        ),
        migrations.DeleteModel(
            name='Content3',
        ),
        migrations.DeleteModel(
            name='Section1',
        ),
        migrations.DeleteModel(
            name='Section2',
        ),
        migrations.DeleteModel(
            name='Section3',
        ),
    ]
